# Fabric Mod Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.java.home=C:\\Users\\liv\\AppData\\Roaming\\PrismLauncher\\java\\java-runtime-epsilon
fabric.loom.disableTargetJavaVersionCheck=true
loom.disableTargetJavaVersionCheck=true

# Minecraft & Fabric Loader/API versions
minecraft_version=26.1.2
loader_version=0.19.3

# Mod Info
mod_version=1.0.0
maven_group=net.livaddons
archives_base_name=livaddons
